name: "WordPress Version Checker"
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  schedule:
    - cron: '0 0 * * 1'

permissions:
  issues: write

jobs:
  wordpress-version-checker:
    # Prevent this workflow to run on forks outside of the GatherPress organization,
    # because the required permission to create an issue would not be given and the workflow would fail.
    # Using a condition check will skip the test.
    if: github.repository_owner == 'GatherPress'
    runs-on: ubuntu-latest
    steps:
      - name: WordPress Version Checker
        uses: skaut/wordpress-version-checker@v2.2.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
